name: bridge tap workflow

on:
  workflow_dispatch:  # This replaces the pull_request trigger with a manual trigger

jobs:
  run-sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3  
        
      - name: Install bridge-utils
        run: |
          pwd
          sudo apt update
          sudo apt install -y iproute2 bridge-utils

      - name: Create VETH Interfaces
        run: |
          pwd
          ip link add dev vm1 type veth peer name vm2
          ip link set dev vm1 up

          
      - name: Create the Bridge
        run: |
          pwd
          ip tuntap add tapm mode tap
          ip link set dev tapm up
          ip link add brm type bridge

      - name: Bring the Bridge Up
        run: |
          pwd
          ip link set tapm master brm
          ip link set vm1 master brm
          ip addr add 10.0.0.1/24 dev brm
          ip addr add 10.0.0.2/24 dev vm2
          ip link set brm up
          ip link set vm2 up

      - name: libfabric bring up
        run: |
          pwd
          cd ..
          wget https://github.com/ofiwg/libfabric/releases/download/v1.20.1/libfabric-1.20.1.tar.bz2
          tar -jxvf libfabric-1.20.1.tar.bz2
          ln -s libfabric-1.20.1 libfabric
          cd libfabric
          autoreconf
          ./configure
          make -j
          
      - name: uet-ref-prov compile
        run: |
          pwd
          make

      - name: Start Server and Client in Parallel
        run: |
          pwd
          sudo LD_LIBRARY_PATH=../libfabric/src/.libs UET_IFNAME=brm ./uet server 10.0.0.2 &
          sleep 5
          sudo LD_LIBRARY_PATH=../libfabric/src/.libs UET_IFNAME=vm2 ./uet client 10.0.0.1
          
